# Generated by Django 4.2.7 on 2025-07-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('data', models.TextField()),
                ('label', models.CharField(blank=True, max_length=255)),
                ('code_type', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('location', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
